@host = http://localhost:3000

### Create User
POST {{host}}/user/signup
Content-Type: application/json

{
    "email": "machado@email.com",
    "password": "12345678"
}

### Login
POST {{host}}/user/signin
Content-Type: application/json

{
    "email": "machado@email.com",
    "password": "12345678"
}

### Get the currently signed in user
GET {{host}}/user/whoami
Content-Type: application/json

### Find a user with given id
GET {{host}}/user/1
Content-Type: application/json

### Find all users by email
GET {{host}}/user/?email=teste@email.com
Content-Type: application/json

### Update user
PATCH {{host}}/user/1
Content-Type: application/json

{
    "email": "breno@email.com"
}

### Delete a user
DELETE {{host}}/user/2

### Set color
GET {{host}}/user/colors/white

### Get color
GET {{host}}/user/colors/

