@host = http://localhost:3000

### Create User
POST {{host}}/user/signup
Content-Type: application/json

{
    "email": "teste@email.com",
    "password": "123456"
}

### Find a user with given id
GET {{host}}/user/1
Content-Type: application/json