
@host = http://localhost:3000

### List all messages
GET {{host}}/message

### Create a new message
POST {{host}}/message
content-type: application/json

{
    "content": "goodbye!"
}

### Get a particular message
GET {{host}}/message/885